/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FastHandsService_CONSTANTS_H
#define FastHandsService_CONSTANTS_H

#include "FastHandsService_types.h"

namespace fasthands {

class FastHandsServiceConstants {
 public:
  FastHandsServiceConstants();

};

extern const FastHandsServiceConstants g_FastHandsService_constants;

} // namespace

#endif
