/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "FastHandsService_constants.h"

namespace fasthands {

const FastHandsServiceConstants g_FastHandsService_constants;

FastHandsServiceConstants::FastHandsServiceConstants() {
}

} // namespace

